
on:
  push:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: |
        yarn install --frozen-lockfile
        yarn deploy
    